/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcMiner.h"

bool_t
xdr_SubmitChallengeRequest (XDR *xdrs, SubmitChallengeRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->transactionId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SeedResponse (XDR *xdrs, SeedResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->challenge))
		 return FALSE;
	return TRUE;
}
