/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCMINER_H_RPCGEN
#define _RPCMINER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SubmitChallengeRequest {
	int transactionId;
	int seed;
	int clientId;
};
typedef struct SubmitChallengeRequest SubmitChallengeRequest;

struct SeedResponse {
	int status;
	int seed;
	int challenge;
};
typedef struct SeedResponse SeedResponse;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define get_transaction_id 1
extern  int * get_transaction_id_100(void *, CLIENT *);
extern  int * get_transaction_id_100_svc(void *, struct svc_req *);
#define get_challenge 2
extern  int * get_challenge_100(int *, CLIENT *);
extern  int * get_challenge_100_svc(int *, struct svc_req *);
#define get_transaction_status 3
extern  int * get_transaction_status_100(int *, CLIENT *);
extern  int * get_transaction_status_100_svc(int *, struct svc_req *);
#define submit_challenge 4
extern  int * submit_challenge_100(SubmitChallengeRequest *, CLIENT *);
extern  int * submit_challenge_100_svc(SubmitChallengeRequest *, struct svc_req *);
#define get_winner 5
extern  int * get_winner_100(int *, CLIENT *);
extern  int * get_winner_100_svc(int *, struct svc_req *);
#define get_seed 6
extern  SeedResponse * get_seed_100(int *, CLIENT *);
extern  SeedResponse * get_seed_100_svc(int *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_transaction_id 1
extern  int * get_transaction_id_100();
extern  int * get_transaction_id_100_svc();
#define get_challenge 2
extern  int * get_challenge_100();
extern  int * get_challenge_100_svc();
#define get_transaction_status 3
extern  int * get_transaction_status_100();
extern  int * get_transaction_status_100_svc();
#define submit_challenge 4
extern  int * submit_challenge_100();
extern  int * submit_challenge_100_svc();
#define get_winner 5
extern  int * get_winner_100();
extern  int * get_winner_100_svc();
#define get_seed 6
extern  SeedResponse * get_seed_100();
extern  SeedResponse * get_seed_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SubmitChallengeRequest (XDR *, SubmitChallengeRequest*);
extern  bool_t xdr_SeedResponse (XDR *, SeedResponse*);

#else /* K&R C */
extern bool_t xdr_SubmitChallengeRequest ();
extern bool_t xdr_SeedResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCMINER_H_RPCGEN */
